# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication , QWidget, QInputDialog , QLineEdit , QFileDialog
from PyQt5.QtGui import QIcon
from PyQt5.QtGui import QPixmap
from skimage import io
from skimage.filters import sobel, gaussian
from skimage import  color, data
from imageio import imsave
import os
from skimage.util import img_as_ubyte
from test3 import Ui_MainWindow2


class Ui_MainWindow1(object):
    def open(self):
        
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.window)
        self.window.show()
   
      
    def Ouvrir(self):
    
        filename= QFileDialog.getOpenFileName()
        a= filename[0]
        path=os.path.basename(a)
        s=io.imread(a)
        pixmap = QPixmap(a)
        self.label.setPixmap(QPixmap(pixmap))
        img_gray = color.rgb2gray(s)
        img_gray= img_as_ubyte(img_gray)
        edge_sobel = sobel(img_gray)
        edge_sobel=img_as_ubyte(edge_sobel)
        new_edged_image = "new_filter "+path
        print(new_edged_image)
        saved_image = io.imsave(new_edged_image, edge_sobel)

        pixmap1 = QPixmap(new_edged_image)
        self.label_2.setPixmap(QPixmap(pixmap1))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.entrer = QtWidgets.QPushButton(self.centralwidget)
        self.entrer.setGeometry(QtCore.QRect(220, 400, 75, 30))
        self.entrer.setObjectName("entrer")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(220, 30, 550, 13))
        self.label2.setObjectName("label2")
        self.suivant = QtWidgets.QPushButton(self.centralwidget)
        self.suivant.setGeometry(QtCore.QRect(400, 420, 75, 23))
        self.suivant.setObjectName("suivant")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 80, 181, 281))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.setScaledContents(True)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 80, 191, 281))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.suivant.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.entrer.clicked.connect(self.Ouvrir)
        self.suivant.clicked.connect(self.open)
      
       
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label2.setText(_translate("MainWindow", "Filtres: Edge detection"))
        self.entrer.setText(_translate("MainWindow", "Appliquer"))
        self.suivant.setText(_translate("MainWindow", "suivant"))
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
